
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.foragecraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.foragecraft.block.YewWoodBlock;
import net.mcreator.foragecraft.block.YewStairsBlock;
import net.mcreator.foragecraft.block.YewSlabBlock;
import net.mcreator.foragecraft.block.YewPressurePlateBlock;
import net.mcreator.foragecraft.block.YewPlanksBlock;
import net.mcreator.foragecraft.block.YewLogBlock;
import net.mcreator.foragecraft.block.YewLeavesBlock;
import net.mcreator.foragecraft.block.YewFenceGateBlock;
import net.mcreator.foragecraft.block.YewFenceBlock;
import net.mcreator.foragecraft.block.YewButtonBlock;
import net.mcreator.foragecraft.block.WychElmWoodBlock;
import net.mcreator.foragecraft.block.WychElmStairsBlock;
import net.mcreator.foragecraft.block.WychElmSlabBlock;
import net.mcreator.foragecraft.block.WychElmPressurePlateBlock;
import net.mcreator.foragecraft.block.WychElmPlanksBlock;
import net.mcreator.foragecraft.block.WychElmLogBlock;
import net.mcreator.foragecraft.block.WychElmLeavesBlock;
import net.mcreator.foragecraft.block.WychElmFenceGateBlock;
import net.mcreator.foragecraft.block.WychElmFenceBlock;
import net.mcreator.foragecraft.block.WychElmButtonBlock;
import net.mcreator.foragecraft.block.WoodSorrelBlock;
import net.mcreator.foragecraft.block.WildGarlicBlock;
import net.mcreator.foragecraft.block.WildCherryWoodBlock;
import net.mcreator.foragecraft.block.WildCherryStairsBlock;
import net.mcreator.foragecraft.block.WildCherrySlabBlock;
import net.mcreator.foragecraft.block.WildCherryPressurePlateBlock;
import net.mcreator.foragecraft.block.WildCherryPlanksBlock;
import net.mcreator.foragecraft.block.WildCherryLogBlock;
import net.mcreator.foragecraft.block.WildCherryLeavesBlock;
import net.mcreator.foragecraft.block.WildCherryFenceGateBlock;
import net.mcreator.foragecraft.block.WildCherryFenceBlock;
import net.mcreator.foragecraft.block.WildCherryButtonBlock;
import net.mcreator.foragecraft.block.WhitebeamWoodBlock;
import net.mcreator.foragecraft.block.WhitebeamStairsBlock;
import net.mcreator.foragecraft.block.WhitebeamSlabBlock;
import net.mcreator.foragecraft.block.WhitebeamPressurePlateBlock;
import net.mcreator.foragecraft.block.WhitebeamPlanksBlock;
import net.mcreator.foragecraft.block.WhitebeamLogBlock;
import net.mcreator.foragecraft.block.WhitebeamLeavesBlock;
import net.mcreator.foragecraft.block.WhitebeamFenceGateBlock;
import net.mcreator.foragecraft.block.WhitebeamFenceBlock;
import net.mcreator.foragecraft.block.WhitebeamButtonBlock;
import net.mcreator.foragecraft.block.SpindleWoodBlock;
import net.mcreator.foragecraft.block.SpindleStairsBlock;
import net.mcreator.foragecraft.block.SpindleSlabBlock;
import net.mcreator.foragecraft.block.SpindlePressurePlateBlock;
import net.mcreator.foragecraft.block.SpindlePlanksBlock;
import net.mcreator.foragecraft.block.SpindleLogBlock;
import net.mcreator.foragecraft.block.SpindleLeavesBlock;
import net.mcreator.foragecraft.block.SpindleFenceGateBlock;
import net.mcreator.foragecraft.block.SpindleFenceBlock;
import net.mcreator.foragecraft.block.SpindleButtonBlock;
import net.mcreator.foragecraft.block.ScotsPineWoodBlock;
import net.mcreator.foragecraft.block.ScotsPineStairsBlock;
import net.mcreator.foragecraft.block.ScotsPineSlabBlock;
import net.mcreator.foragecraft.block.ScotsPinePressurePlateBlock;
import net.mcreator.foragecraft.block.ScotsPinePlanksBlock;
import net.mcreator.foragecraft.block.ScotsPineLogBlock;
import net.mcreator.foragecraft.block.ScotsPineLeavesBlock;
import net.mcreator.foragecraft.block.ScotsPineFenceGateBlock;
import net.mcreator.foragecraft.block.ScotsPineFenceBlock;
import net.mcreator.foragecraft.block.ScotsPineButtonBlock;
import net.mcreator.foragecraft.block.SampireBlock;
import net.mcreator.foragecraft.block.RowanWoodBlock;
import net.mcreator.foragecraft.block.RowanStairsBlock;
import net.mcreator.foragecraft.block.RowanSlabBlock;
import net.mcreator.foragecraft.block.RowanPressurePlateBlock;
import net.mcreator.foragecraft.block.RowanPlanksBlock;
import net.mcreator.foragecraft.block.RowanLogBlock;
import net.mcreator.foragecraft.block.RowanLeavesBlock;
import net.mcreator.foragecraft.block.RowanFenceGateBlock;
import net.mcreator.foragecraft.block.RowanFenceBlock;
import net.mcreator.foragecraft.block.RowanButtonBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornWoodBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornStairsBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornSlabBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornPressurePlateBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornPlanksBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornLogBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornLeavesBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornFenceGateBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornFenceBlock;
import net.mcreator.foragecraft.block.PurgingBuckthornButtonBlock;
import net.mcreator.foragecraft.block.PuffballBlock;
import net.mcreator.foragecraft.block.PlymouthPearWoodBlock;
import net.mcreator.foragecraft.block.PlymouthPearStairsBlock;
import net.mcreator.foragecraft.block.PlymouthPearSlabBlock;
import net.mcreator.foragecraft.block.PlymouthPearPressurePlateBlock;
import net.mcreator.foragecraft.block.PlymouthPearPlanksBlock;
import net.mcreator.foragecraft.block.PlymouthPearLogBlock;
import net.mcreator.foragecraft.block.PlymouthPearLeavesBlock;
import net.mcreator.foragecraft.block.PlymouthPearFenceGateBlock;
import net.mcreator.foragecraft.block.PlymouthPearFenceBlock;
import net.mcreator.foragecraft.block.PlymouthPearButtonBlock;
import net.mcreator.foragecraft.block.ParasolMushroomBlock;
import net.mcreator.foragecraft.block.NettleBlock;
import net.mcreator.foragecraft.block.JuniperWoodBlock;
import net.mcreator.foragecraft.block.JuniperStairsBlock;
import net.mcreator.foragecraft.block.JuniperSlabBlock;
import net.mcreator.foragecraft.block.JuniperPressurePlateBlock;
import net.mcreator.foragecraft.block.JuniperPlanksBlock;
import net.mcreator.foragecraft.block.JuniperLogBlock;
import net.mcreator.foragecraft.block.JuniperLeavesBlock;
import net.mcreator.foragecraft.block.JuniperFenceGateBlock;
import net.mcreator.foragecraft.block.JuniperFenceBlock;
import net.mcreator.foragecraft.block.JuniperButtonBlock;
import net.mcreator.foragecraft.block.HornbeamWoodBlock;
import net.mcreator.foragecraft.block.HornbeamStairsBlock;
import net.mcreator.foragecraft.block.HornbeamSlabBlock;
import net.mcreator.foragecraft.block.HornbeamPressurePlateBlock;
import net.mcreator.foragecraft.block.HornbeamPlanksBlock;
import net.mcreator.foragecraft.block.HornbeamLogBlock;
import net.mcreator.foragecraft.block.HornbeamLeavesBlock;
import net.mcreator.foragecraft.block.HornbeamFenceGateBlock;
import net.mcreator.foragecraft.block.HornbeamFenceBlock;
import net.mcreator.foragecraft.block.HornbeamButtonBlock;
import net.mcreator.foragecraft.block.HemlockBlock;
import net.mcreator.foragecraft.block.HawthornplankBlock;
import net.mcreator.foragecraft.block.HawthornlogBlock;
import net.mcreator.foragecraft.block.HawthornleavesberriesBlock;
import net.mcreator.foragecraft.block.HawthornleavesBlock;
import net.mcreator.foragecraft.block.HawthornSaplingBlock;
import net.mcreator.foragecraft.block.GreyWillowWoodBlock;
import net.mcreator.foragecraft.block.GreyWillowStairsBlock;
import net.mcreator.foragecraft.block.GreyWillowSlabBlock;
import net.mcreator.foragecraft.block.GreyWillowPressurePlateBlock;
import net.mcreator.foragecraft.block.GreyWillowPlanksBlock;
import net.mcreator.foragecraft.block.GreyWillowLogBlock;
import net.mcreator.foragecraft.block.GreyWillowLeavesBlock;
import net.mcreator.foragecraft.block.GreyWillowFenceGateBlock;
import net.mcreator.foragecraft.block.GreyWillowFenceBlock;
import net.mcreator.foragecraft.block.GreyWillowButtonBlock;
import net.mcreator.foragecraft.block.GoatWillowWoodBlock;
import net.mcreator.foragecraft.block.GoatWillowStairsBlock;
import net.mcreator.foragecraft.block.GoatWillowSlabBlock;
import net.mcreator.foragecraft.block.GoatWillowPressurePlateBlock;
import net.mcreator.foragecraft.block.GoatWillowPlanksBlock;
import net.mcreator.foragecraft.block.GoatWillowLogBlock;
import net.mcreator.foragecraft.block.GoatWillowLeavesBlock;
import net.mcreator.foragecraft.block.GoatWillowFenceGateBlock;
import net.mcreator.foragecraft.block.GoatWillowFenceBlock;
import net.mcreator.foragecraft.block.GoatWillowButtonBlock;
import net.mcreator.foragecraft.block.FlyAgaricBlock;
import net.mcreator.foragecraft.block.FieldMapleWoodBlock;
import net.mcreator.foragecraft.block.FieldMapleStairsBlock;
import net.mcreator.foragecraft.block.FieldMapleSlabBlock;
import net.mcreator.foragecraft.block.FieldMaplePressurePlateBlock;
import net.mcreator.foragecraft.block.FieldMaplePlanksBlock;
import net.mcreator.foragecraft.block.FieldMapleLogBlock;
import net.mcreator.foragecraft.block.FieldMapleLeavesBlock;
import net.mcreator.foragecraft.block.FieldMapleFenceGateBlock;
import net.mcreator.foragecraft.block.FieldMapleFenceBlock;
import net.mcreator.foragecraft.block.FieldMapleButtonBlock;
import net.mcreator.foragecraft.block.EnglishElmWoodBlock;
import net.mcreator.foragecraft.block.EnglishElmStairsBlock;
import net.mcreator.foragecraft.block.EnglishElmSlabBlock;
import net.mcreator.foragecraft.block.EnglishElmPressurePlateBlock;
import net.mcreator.foragecraft.block.EnglishElmPlanksBlock;
import net.mcreator.foragecraft.block.EnglishElmLogBlock;
import net.mcreator.foragecraft.block.EnglishElmLeavesBlock;
import net.mcreator.foragecraft.block.EnglishElmFenceGateBlock;
import net.mcreator.foragecraft.block.EnglishElmFenceBlock;
import net.mcreator.foragecraft.block.EnglishElmButtonBlock;
import net.mcreator.foragecraft.block.ElderWoodBlock;
import net.mcreator.foragecraft.block.ElderStairsBlock;
import net.mcreator.foragecraft.block.ElderSlabBlock;
import net.mcreator.foragecraft.block.ElderPressurePlateBlock;
import net.mcreator.foragecraft.block.ElderPlanksBlock;
import net.mcreator.foragecraft.block.ElderLogBlock;
import net.mcreator.foragecraft.block.ElderLeavesBlock;
import net.mcreator.foragecraft.block.ElderFenceGateBlock;
import net.mcreator.foragecraft.block.ElderFenceBlock;
import net.mcreator.foragecraft.block.ElderButtonBlock;
import net.mcreator.foragecraft.block.DownyBirchWoodBlock;
import net.mcreator.foragecraft.block.DownyBirchStairsBlock;
import net.mcreator.foragecraft.block.DownyBirchSlabBlock;
import net.mcreator.foragecraft.block.DownyBirchPressurePlateBlock;
import net.mcreator.foragecraft.block.DownyBirchPlanksBlock;
import net.mcreator.foragecraft.block.DownyBirchLogBlock;
import net.mcreator.foragecraft.block.DownyBirchLeavesBlock;
import net.mcreator.foragecraft.block.DownyBirchFenceGateBlock;
import net.mcreator.foragecraft.block.DownyBirchFenceBlock;
import net.mcreator.foragecraft.block.DownyBirchButtonBlock;
import net.mcreator.foragecraft.block.DehydratorBlock;
import net.mcreator.foragecraft.block.DandelionBlock;
import net.mcreator.foragecraft.block.CrabappleWoodBlock;
import net.mcreator.foragecraft.block.CrabappleStairsBlock;
import net.mcreator.foragecraft.block.CrabappleSlabBlock;
import net.mcreator.foragecraft.block.CrabapplePressurePlateBlock;
import net.mcreator.foragecraft.block.CrabapplePlanksBlock;
import net.mcreator.foragecraft.block.CrabappleLogBlock;
import net.mcreator.foragecraft.block.CrabappleLeavesBlock;
import net.mcreator.foragecraft.block.CrabappleFenceGateBlock;
import net.mcreator.foragecraft.block.CrabappleFenceBlock;
import net.mcreator.foragecraft.block.CrabappleButtonBlock;
import net.mcreator.foragecraft.block.CookingPotBlock;
import net.mcreator.foragecraft.block.CommonLimeWoodBlock;
import net.mcreator.foragecraft.block.CommonLimeStairsBlock;
import net.mcreator.foragecraft.block.CommonLimeSlabBlock;
import net.mcreator.foragecraft.block.CommonLimePressurePlateBlock;
import net.mcreator.foragecraft.block.CommonLimePlanksBlock;
import net.mcreator.foragecraft.block.CommonLimeLogBlock;
import net.mcreator.foragecraft.block.CommonLimeLeavesBlock;
import net.mcreator.foragecraft.block.CommonLimeFenceGateBlock;
import net.mcreator.foragecraft.block.CommonLimeFenceBlock;
import net.mcreator.foragecraft.block.CommonLimeButtonBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodTrapdoorBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodStairsBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodSlabBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodPlanksBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodLogBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodFenceGateBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodFenceBlock;
import net.mcreator.foragecraft.block.CommonBeechWoodDoorBlock;
import net.mcreator.foragecraft.block.CommonBeechSaplingBlock;
import net.mcreator.foragecraft.block.CommonBeechLeavesBlock;
import net.mcreator.foragecraft.block.ChanterelleBlock;
import net.mcreator.foragecraft.block.CepBlock;
import net.mcreator.foragecraft.block.CampfireBlock;
import net.mcreator.foragecraft.block.BluebellsBlock;
import net.mcreator.foragecraft.block.BlewitBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamWoodBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamStairsBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamSlabBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamPressurePlateBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamPlanksBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamLogBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamLeavesBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamFenceGateBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamFenceBlock;
import net.mcreator.foragecraft.block.BlackWhitebeamButtonBlock;
import net.mcreator.foragecraft.block.BlackPoplarWoodBlock;
import net.mcreator.foragecraft.block.BlackPoplarStairsBlock;
import net.mcreator.foragecraft.block.BlackPoplarSlabBlock;
import net.mcreator.foragecraft.block.BlackPoplarPressurePlateBlock;
import net.mcreator.foragecraft.block.BlackPoplarPlanksBlock;
import net.mcreator.foragecraft.block.BlackPoplarLogBlock;
import net.mcreator.foragecraft.block.BlackPoplarLeavesBlock;
import net.mcreator.foragecraft.block.BlackPoplarFenceGateBlock;
import net.mcreator.foragecraft.block.BlackPoplarFenceBlock;
import net.mcreator.foragecraft.block.BlackPoplarButtonBlock;
import net.mcreator.foragecraft.block.BirdCherryWoodBlock;
import net.mcreator.foragecraft.block.BirdCherryStairsBlock;
import net.mcreator.foragecraft.block.BirdCherrySlabBlock;
import net.mcreator.foragecraft.block.BirdCherryPressurePlateBlock;
import net.mcreator.foragecraft.block.BirdCherryPlanksBlock;
import net.mcreator.foragecraft.block.BirdCherryLogBlock;
import net.mcreator.foragecraft.block.BirdCherryLeavesBlock;
import net.mcreator.foragecraft.block.BirdCherryFenceGateBlock;
import net.mcreator.foragecraft.block.BirdCherryFenceBlock;
import net.mcreator.foragecraft.block.BirdCherryButtonBlock;
import net.mcreator.foragecraft.block.BayWillowWoodBlock;
import net.mcreator.foragecraft.block.BayWillowStairsBlock;
import net.mcreator.foragecraft.block.BayWillowSlabBlock;
import net.mcreator.foragecraft.block.BayWillowPressurePlateBlock;
import net.mcreator.foragecraft.block.BayWillowPlanksBlock;
import net.mcreator.foragecraft.block.BayWillowLogBlock;
import net.mcreator.foragecraft.block.BayWillowLeavesBlock;
import net.mcreator.foragecraft.block.BayWillowFenceGateBlock;
import net.mcreator.foragecraft.block.BayWillowFenceBlock;
import net.mcreator.foragecraft.block.BayWillowButtonBlock;
import net.mcreator.foragecraft.block.AspenWoodBlock;
import net.mcreator.foragecraft.block.AspenStairsBlock;
import net.mcreator.foragecraft.block.AspenSlabBlock;
import net.mcreator.foragecraft.block.AspenPressurePlateBlock;
import net.mcreator.foragecraft.block.AspenPlanksBlock;
import net.mcreator.foragecraft.block.AspenLogBlock;
import net.mcreator.foragecraft.block.AspenLeavesBlock;
import net.mcreator.foragecraft.block.AspenFenceGateBlock;
import net.mcreator.foragecraft.block.AspenFenceBlock;
import net.mcreator.foragecraft.block.AspenButtonBlock;
import net.mcreator.foragecraft.block.AshWoodBlock;
import net.mcreator.foragecraft.block.AshStairsBlock;
import net.mcreator.foragecraft.block.AshSlabBlock;
import net.mcreator.foragecraft.block.AshPressurePlateBlock;
import net.mcreator.foragecraft.block.AshPlanksBlock;
import net.mcreator.foragecraft.block.AshLogBlock;
import net.mcreator.foragecraft.block.AshLeavesBlock;
import net.mcreator.foragecraft.block.AshFenceGateBlock;
import net.mcreator.foragecraft.block.AshFenceBlock;
import net.mcreator.foragecraft.block.AshButtonBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamWoodBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamStairsBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamSlabBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamPressurePlateBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamPlanksBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamLogBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamLeavesBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamFenceGateBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamFenceBlock;
import net.mcreator.foragecraft.block.ArranWhitebeamButtonBlock;
import net.mcreator.foragecraft.block.AlderwoodlogBlock;
import net.mcreator.foragecraft.block.AlderWoodPlanksBlock;
import net.mcreator.foragecraft.block.AlderLeavesBlock;
import net.mcreator.foragecraft.ForagecraftMod;

public class ForagecraftModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ForagecraftMod.MODID);
	public static final RegistryObject<Block> NETTLE = REGISTRY.register("nettle", () -> new NettleBlock());
	public static final RegistryObject<Block> DANDELION = REGISTRY.register("dandelion", () -> new DandelionBlock());
	public static final RegistryObject<Block> WILD_GARLIC = REGISTRY.register("wild_garlic", () -> new WildGarlicBlock());
	public static final RegistryObject<Block> WOOD_SORREL = REGISTRY.register("wood_sorrel", () -> new WoodSorrelBlock());
	public static final RegistryObject<Block> HEMLOCK = REGISTRY.register("hemlock", () -> new HemlockBlock());
	public static final RegistryObject<Block> CEP = REGISTRY.register("cep", () -> new CepBlock());
	public static final RegistryObject<Block> BLEWIT = REGISTRY.register("blewit", () -> new BlewitBlock());
	public static final RegistryObject<Block> PUFFBALL = REGISTRY.register("puffball", () -> new PuffballBlock());
	public static final RegistryObject<Block> FLY_AGARIC = REGISTRY.register("fly_agaric", () -> new FlyAgaricBlock());
	public static final RegistryObject<Block> PARASOL_MUSHROOM = REGISTRY.register("parasol_mushroom", () -> new ParasolMushroomBlock());
	public static final RegistryObject<Block> CHANTERELLE = REGISTRY.register("chanterelle", () -> new ChanterelleBlock());
	public static final RegistryObject<Block> DEHYDRATOR = REGISTRY.register("dehydrator", () -> new DehydratorBlock());
	public static final RegistryObject<Block> CAMPFIRE = REGISTRY.register("campfire", () -> new CampfireBlock());
	public static final RegistryObject<Block> COOKING_POT = REGISTRY.register("cooking_pot", () -> new CookingPotBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_PLANKS = REGISTRY.register("common_beech_wood_planks", () -> new CommonBeechWoodPlanksBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_LOG = REGISTRY.register("common_beech_wood_log", () -> new CommonBeechWoodLogBlock());
	public static final RegistryObject<Block> COMMON_BEECH_SAPLING = REGISTRY.register("common_beech_sapling", () -> new CommonBeechSaplingBlock());
	public static final RegistryObject<Block> COMMON_BEECH_LEAVES = REGISTRY.register("common_beech_leaves", () -> new CommonBeechLeavesBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_STAIRS = REGISTRY.register("common_beech_wood_stairs", () -> new CommonBeechWoodStairsBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_SLAB = REGISTRY.register("common_beech_wood_slab", () -> new CommonBeechWoodSlabBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_FENCE = REGISTRY.register("common_beech_wood_fence", () -> new CommonBeechWoodFenceBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_FENCE_GATE = REGISTRY.register("common_beech_wood_fence_gate", () -> new CommonBeechWoodFenceGateBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_TRAPDOOR = REGISTRY.register("common_beech_wood_trapdoor", () -> new CommonBeechWoodTrapdoorBlock());
	public static final RegistryObject<Block> COMMON_BEECH_WOOD_DOOR = REGISTRY.register("common_beech_wood_door", () -> new CommonBeechWoodDoorBlock());
	public static final RegistryObject<Block> HAWTHORNLOG = REGISTRY.register("hawthornlog", () -> new HawthornlogBlock());
	public static final RegistryObject<Block> HAWTHORNLEAVES = REGISTRY.register("hawthornleaves", () -> new HawthornleavesBlock());
	public static final RegistryObject<Block> HAWTHORNLEAVESBERRIES = REGISTRY.register("hawthornleavesberries", () -> new HawthornleavesberriesBlock());
	public static final RegistryObject<Block> HAWTHORNPLANK = REGISTRY.register("hawthornplank", () -> new HawthornplankBlock());
	public static final RegistryObject<Block> HAWTHORN_SAPLING = REGISTRY.register("hawthorn_sapling", () -> new HawthornSaplingBlock());
	public static final RegistryObject<Block> YEW_WOOD = REGISTRY.register("yew_wood", () -> new YewWoodBlock());
	public static final RegistryObject<Block> ALDERWOODLOG = REGISTRY.register("alderwoodlog", () -> new AlderwoodlogBlock());
	public static final RegistryObject<Block> YEW_LOG = REGISTRY.register("yew_log", () -> new YewLogBlock());
	public static final RegistryObject<Block> YEW_PLANKS = REGISTRY.register("yew_planks", () -> new YewPlanksBlock());
	public static final RegistryObject<Block> YEW_LEAVES = REGISTRY.register("yew_leaves", () -> new YewLeavesBlock());
	public static final RegistryObject<Block> YEW_STAIRS = REGISTRY.register("yew_stairs", () -> new YewStairsBlock());
	public static final RegistryObject<Block> YEW_SLAB = REGISTRY.register("yew_slab", () -> new YewSlabBlock());
	public static final RegistryObject<Block> YEW_FENCE = REGISTRY.register("yew_fence", () -> new YewFenceBlock());
	public static final RegistryObject<Block> YEW_FENCE_GATE = REGISTRY.register("yew_fence_gate", () -> new YewFenceGateBlock());
	public static final RegistryObject<Block> YEW_PRESSURE_PLATE = REGISTRY.register("yew_pressure_plate", () -> new YewPressurePlateBlock());
	public static final RegistryObject<Block> YEW_BUTTON = REGISTRY.register("yew_button", () -> new YewButtonBlock());
	public static final RegistryObject<Block> ASH_WOOD = REGISTRY.register("ash_wood", () -> new AshWoodBlock());
	public static final RegistryObject<Block> ASH_LOG = REGISTRY.register("ash_log", () -> new AshLogBlock());
	public static final RegistryObject<Block> ASH_PLANKS = REGISTRY.register("ash_planks", () -> new AshPlanksBlock());
	public static final RegistryObject<Block> ASH_LEAVES = REGISTRY.register("ash_leaves", () -> new AshLeavesBlock());
	public static final RegistryObject<Block> ASH_STAIRS = REGISTRY.register("ash_stairs", () -> new AshStairsBlock());
	public static final RegistryObject<Block> ASH_SLAB = REGISTRY.register("ash_slab", () -> new AshSlabBlock());
	public static final RegistryObject<Block> ASH_FENCE = REGISTRY.register("ash_fence", () -> new AshFenceBlock());
	public static final RegistryObject<Block> ASH_FENCE_GATE = REGISTRY.register("ash_fence_gate", () -> new AshFenceGateBlock());
	public static final RegistryObject<Block> ASH_PRESSURE_PLATE = REGISTRY.register("ash_pressure_plate", () -> new AshPressurePlateBlock());
	public static final RegistryObject<Block> ASH_BUTTON = REGISTRY.register("ash_button", () -> new AshButtonBlock());
	public static final RegistryObject<Block> ASPEN_WOOD = REGISTRY.register("aspen_wood", () -> new AspenWoodBlock());
	public static final RegistryObject<Block> ASPEN_LOG = REGISTRY.register("aspen_log", () -> new AspenLogBlock());
	public static final RegistryObject<Block> ASPEN_PLANKS = REGISTRY.register("aspen_planks", () -> new AspenPlanksBlock());
	public static final RegistryObject<Block> ASPEN_LEAVES = REGISTRY.register("aspen_leaves", () -> new AspenLeavesBlock());
	public static final RegistryObject<Block> ASPEN_STAIRS = REGISTRY.register("aspen_stairs", () -> new AspenStairsBlock());
	public static final RegistryObject<Block> ASPEN_SLAB = REGISTRY.register("aspen_slab", () -> new AspenSlabBlock());
	public static final RegistryObject<Block> ASPEN_FENCE = REGISTRY.register("aspen_fence", () -> new AspenFenceBlock());
	public static final RegistryObject<Block> ASPEN_FENCE_GATE = REGISTRY.register("aspen_fence_gate", () -> new AspenFenceGateBlock());
	public static final RegistryObject<Block> ASPEN_PRESSURE_PLATE = REGISTRY.register("aspen_pressure_plate", () -> new AspenPressurePlateBlock());
	public static final RegistryObject<Block> ASPEN_BUTTON = REGISTRY.register("aspen_button", () -> new AspenButtonBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_WOOD = REGISTRY.register("downy_birch_wood", () -> new DownyBirchWoodBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_LOG = REGISTRY.register("downy_birch_log", () -> new DownyBirchLogBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_PLANKS = REGISTRY.register("downy_birch_planks", () -> new DownyBirchPlanksBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_LEAVES = REGISTRY.register("downy_birch_leaves", () -> new DownyBirchLeavesBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_STAIRS = REGISTRY.register("downy_birch_stairs", () -> new DownyBirchStairsBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_SLAB = REGISTRY.register("downy_birch_slab", () -> new DownyBirchSlabBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_FENCE = REGISTRY.register("downy_birch_fence", () -> new DownyBirchFenceBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_FENCE_GATE = REGISTRY.register("downy_birch_fence_gate", () -> new DownyBirchFenceGateBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_PRESSURE_PLATE = REGISTRY.register("downy_birch_pressure_plate", () -> new DownyBirchPressurePlateBlock());
	public static final RegistryObject<Block> DOWNY_BIRCH_BUTTON = REGISTRY.register("downy_birch_button", () -> new DownyBirchButtonBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_WOOD = REGISTRY.register("purging_buckthorn_wood", () -> new PurgingBuckthornWoodBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_LOG = REGISTRY.register("purging_buckthorn_log", () -> new PurgingBuckthornLogBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_PLANKS = REGISTRY.register("purging_buckthorn_planks", () -> new PurgingBuckthornPlanksBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_LEAVES = REGISTRY.register("purging_buckthorn_leaves", () -> new PurgingBuckthornLeavesBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_STAIRS = REGISTRY.register("purging_buckthorn_stairs", () -> new PurgingBuckthornStairsBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_SLAB = REGISTRY.register("purging_buckthorn_slab", () -> new PurgingBuckthornSlabBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_FENCE = REGISTRY.register("purging_buckthorn_fence", () -> new PurgingBuckthornFenceBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_FENCE_GATE = REGISTRY.register("purging_buckthorn_fence_gate", () -> new PurgingBuckthornFenceGateBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_PRESSURE_PLATE = REGISTRY.register("purging_buckthorn_pressure_plate", () -> new PurgingBuckthornPressurePlateBlock());
	public static final RegistryObject<Block> PURGING_BUCKTHORN_BUTTON = REGISTRY.register("purging_buckthorn_button", () -> new PurgingBuckthornButtonBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_WOOD = REGISTRY.register("bird_cherry_wood", () -> new BirdCherryWoodBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_LOG = REGISTRY.register("bird_cherry_log", () -> new BirdCherryLogBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_PLANKS = REGISTRY.register("bird_cherry_planks", () -> new BirdCherryPlanksBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_LEAVES = REGISTRY.register("bird_cherry_leaves", () -> new BirdCherryLeavesBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_STAIRS = REGISTRY.register("bird_cherry_stairs", () -> new BirdCherryStairsBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_SLAB = REGISTRY.register("bird_cherry_slab", () -> new BirdCherrySlabBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_FENCE = REGISTRY.register("bird_cherry_fence", () -> new BirdCherryFenceBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_FENCE_GATE = REGISTRY.register("bird_cherry_fence_gate", () -> new BirdCherryFenceGateBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_PRESSURE_PLATE = REGISTRY.register("bird_cherry_pressure_plate", () -> new BirdCherryPressurePlateBlock());
	public static final RegistryObject<Block> BIRD_CHERRY_BUTTON = REGISTRY.register("bird_cherry_button", () -> new BirdCherryButtonBlock());
	public static final RegistryObject<Block> WILD_CHERRY_WOOD = REGISTRY.register("wild_cherry_wood", () -> new WildCherryWoodBlock());
	public static final RegistryObject<Block> WILD_CHERRY_LOG = REGISTRY.register("wild_cherry_log", () -> new WildCherryLogBlock());
	public static final RegistryObject<Block> WILD_CHERRY_PLANKS = REGISTRY.register("wild_cherry_planks", () -> new WildCherryPlanksBlock());
	public static final RegistryObject<Block> WILD_CHERRY_LEAVES = REGISTRY.register("wild_cherry_leaves", () -> new WildCherryLeavesBlock());
	public static final RegistryObject<Block> WILD_CHERRY_STAIRS = REGISTRY.register("wild_cherry_stairs", () -> new WildCherryStairsBlock());
	public static final RegistryObject<Block> WILD_CHERRY_SLAB = REGISTRY.register("wild_cherry_slab", () -> new WildCherrySlabBlock());
	public static final RegistryObject<Block> WILD_CHERRY_FENCE = REGISTRY.register("wild_cherry_fence", () -> new WildCherryFenceBlock());
	public static final RegistryObject<Block> WILD_CHERRY_FENCE_GATE = REGISTRY.register("wild_cherry_fence_gate", () -> new WildCherryFenceGateBlock());
	public static final RegistryObject<Block> WILD_CHERRY_PRESSURE_PLATE = REGISTRY.register("wild_cherry_pressure_plate", () -> new WildCherryPressurePlateBlock());
	public static final RegistryObject<Block> WILD_CHERRY_BUTTON = REGISTRY.register("wild_cherry_button", () -> new WildCherryButtonBlock());
	public static final RegistryObject<Block> CRABAPPLE_WOOD = REGISTRY.register("crabapple_wood", () -> new CrabappleWoodBlock());
	public static final RegistryObject<Block> CRABAPPLE_LOG = REGISTRY.register("crabapple_log", () -> new CrabappleLogBlock());
	public static final RegistryObject<Block> CRABAPPLE_PLANKS = REGISTRY.register("crabapple_planks", () -> new CrabapplePlanksBlock());
	public static final RegistryObject<Block> CRABAPPLE_LEAVES = REGISTRY.register("crabapple_leaves", () -> new CrabappleLeavesBlock());
	public static final RegistryObject<Block> CRABAPPLE_STAIRS = REGISTRY.register("crabapple_stairs", () -> new CrabappleStairsBlock());
	public static final RegistryObject<Block> CRABAPPLE_SLAB = REGISTRY.register("crabapple_slab", () -> new CrabappleSlabBlock());
	public static final RegistryObject<Block> CRABAPPLE_FENCE = REGISTRY.register("crabapple_fence", () -> new CrabappleFenceBlock());
	public static final RegistryObject<Block> CRABAPPLE_FENCE_GATE = REGISTRY.register("crabapple_fence_gate", () -> new CrabappleFenceGateBlock());
	public static final RegistryObject<Block> CRABAPPLE_PRESSURE_PLATE = REGISTRY.register("crabapple_pressure_plate", () -> new CrabapplePressurePlateBlock());
	public static final RegistryObject<Block> CRABAPPLE_BUTTON = REGISTRY.register("crabapple_button", () -> new CrabappleButtonBlock());
	public static final RegistryObject<Block> ELDER_WOOD = REGISTRY.register("elder_wood", () -> new ElderWoodBlock());
	public static final RegistryObject<Block> ELDER_LOG = REGISTRY.register("elder_log", () -> new ElderLogBlock());
	public static final RegistryObject<Block> ELDER_PLANKS = REGISTRY.register("elder_planks", () -> new ElderPlanksBlock());
	public static final RegistryObject<Block> ELDER_LEAVES = REGISTRY.register("elder_leaves", () -> new ElderLeavesBlock());
	public static final RegistryObject<Block> ELDER_STAIRS = REGISTRY.register("elder_stairs", () -> new ElderStairsBlock());
	public static final RegistryObject<Block> ELDER_SLAB = REGISTRY.register("elder_slab", () -> new ElderSlabBlock());
	public static final RegistryObject<Block> ELDER_FENCE = REGISTRY.register("elder_fence", () -> new ElderFenceBlock());
	public static final RegistryObject<Block> ELDER_FENCE_GATE = REGISTRY.register("elder_fence_gate", () -> new ElderFenceGateBlock());
	public static final RegistryObject<Block> ELDER_PRESSURE_PLATE = REGISTRY.register("elder_pressure_plate", () -> new ElderPressurePlateBlock());
	public static final RegistryObject<Block> ELDER_BUTTON = REGISTRY.register("elder_button", () -> new ElderButtonBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_WOOD = REGISTRY.register("english_elm_wood", () -> new EnglishElmWoodBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_LOG = REGISTRY.register("english_elm_log", () -> new EnglishElmLogBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_PLANKS = REGISTRY.register("english_elm_planks", () -> new EnglishElmPlanksBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_LEAVES = REGISTRY.register("english_elm_leaves", () -> new EnglishElmLeavesBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_STAIRS = REGISTRY.register("english_elm_stairs", () -> new EnglishElmStairsBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_SLAB = REGISTRY.register("english_elm_slab", () -> new EnglishElmSlabBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_FENCE = REGISTRY.register("english_elm_fence", () -> new EnglishElmFenceBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_FENCE_GATE = REGISTRY.register("english_elm_fence_gate", () -> new EnglishElmFenceGateBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_PRESSURE_PLATE = REGISTRY.register("english_elm_pressure_plate", () -> new EnglishElmPressurePlateBlock());
	public static final RegistryObject<Block> ENGLISH_ELM_BUTTON = REGISTRY.register("english_elm_button", () -> new EnglishElmButtonBlock());
	public static final RegistryObject<Block> WYCH_ELM_WOOD = REGISTRY.register("wych_elm_wood", () -> new WychElmWoodBlock());
	public static final RegistryObject<Block> WYCH_ELM_LOG = REGISTRY.register("wych_elm_log", () -> new WychElmLogBlock());
	public static final RegistryObject<Block> WYCH_ELM_PLANKS = REGISTRY.register("wych_elm_planks", () -> new WychElmPlanksBlock());
	public static final RegistryObject<Block> WYCH_ELM_LEAVES = REGISTRY.register("wych_elm_leaves", () -> new WychElmLeavesBlock());
	public static final RegistryObject<Block> WYCH_ELM_STAIRS = REGISTRY.register("wych_elm_stairs", () -> new WychElmStairsBlock());
	public static final RegistryObject<Block> WYCH_ELM_SLAB = REGISTRY.register("wych_elm_slab", () -> new WychElmSlabBlock());
	public static final RegistryObject<Block> WYCH_ELM_FENCE = REGISTRY.register("wych_elm_fence", () -> new WychElmFenceBlock());
	public static final RegistryObject<Block> WYCH_ELM_FENCE_GATE = REGISTRY.register("wych_elm_fence_gate", () -> new WychElmFenceGateBlock());
	public static final RegistryObject<Block> WYCH_ELM_PRESSURE_PLATE = REGISTRY.register("wych_elm_pressure_plate", () -> new WychElmPressurePlateBlock());
	public static final RegistryObject<Block> WYCH_ELM_BUTTON = REGISTRY.register("wych_elm_button", () -> new WychElmButtonBlock());
	public static final RegistryObject<Block> HORNBEAM_WOOD = REGISTRY.register("hornbeam_wood", () -> new HornbeamWoodBlock());
	public static final RegistryObject<Block> HORNBEAM_LOG = REGISTRY.register("hornbeam_log", () -> new HornbeamLogBlock());
	public static final RegistryObject<Block> HORNBEAM_PLANKS = REGISTRY.register("hornbeam_planks", () -> new HornbeamPlanksBlock());
	public static final RegistryObject<Block> HORNBEAM_LEAVES = REGISTRY.register("hornbeam_leaves", () -> new HornbeamLeavesBlock());
	public static final RegistryObject<Block> HORNBEAM_STAIRS = REGISTRY.register("hornbeam_stairs", () -> new HornbeamStairsBlock());
	public static final RegistryObject<Block> HORNBEAM_SLAB = REGISTRY.register("hornbeam_slab", () -> new HornbeamSlabBlock());
	public static final RegistryObject<Block> HORNBEAM_FENCE = REGISTRY.register("hornbeam_fence", () -> new HornbeamFenceBlock());
	public static final RegistryObject<Block> HORNBEAM_FENCE_GATE = REGISTRY.register("hornbeam_fence_gate", () -> new HornbeamFenceGateBlock());
	public static final RegistryObject<Block> HORNBEAM_PRESSURE_PLATE = REGISTRY.register("hornbeam_pressure_plate", () -> new HornbeamPressurePlateBlock());
	public static final RegistryObject<Block> HORNBEAM_BUTTON = REGISTRY.register("hornbeam_button", () -> new HornbeamButtonBlock());
	public static final RegistryObject<Block> JUNIPER_WOOD = REGISTRY.register("juniper_wood", () -> new JuniperWoodBlock());
	public static final RegistryObject<Block> JUNIPER_LOG = REGISTRY.register("juniper_log", () -> new JuniperLogBlock());
	public static final RegistryObject<Block> JUNIPER_PLANKS = REGISTRY.register("juniper_planks", () -> new JuniperPlanksBlock());
	public static final RegistryObject<Block> JUNIPER_LEAVES = REGISTRY.register("juniper_leaves", () -> new JuniperLeavesBlock());
	public static final RegistryObject<Block> JUNIPER_STAIRS = REGISTRY.register("juniper_stairs", () -> new JuniperStairsBlock());
	public static final RegistryObject<Block> JUNIPER_SLAB = REGISTRY.register("juniper_slab", () -> new JuniperSlabBlock());
	public static final RegistryObject<Block> JUNIPER_FENCE = REGISTRY.register("juniper_fence", () -> new JuniperFenceBlock());
	public static final RegistryObject<Block> JUNIPER_FENCE_GATE = REGISTRY.register("juniper_fence_gate", () -> new JuniperFenceGateBlock());
	public static final RegistryObject<Block> JUNIPER_PRESSURE_PLATE = REGISTRY.register("juniper_pressure_plate", () -> new JuniperPressurePlateBlock());
	public static final RegistryObject<Block> JUNIPER_BUTTON = REGISTRY.register("juniper_button", () -> new JuniperButtonBlock());
	public static final RegistryObject<Block> COMMON_LIME_WOOD = REGISTRY.register("common_lime_wood", () -> new CommonLimeWoodBlock());
	public static final RegistryObject<Block> COMMON_LIME_LOG = REGISTRY.register("common_lime_log", () -> new CommonLimeLogBlock());
	public static final RegistryObject<Block> COMMON_LIME_PLANKS = REGISTRY.register("common_lime_planks", () -> new CommonLimePlanksBlock());
	public static final RegistryObject<Block> COMMON_LIME_LEAVES = REGISTRY.register("common_lime_leaves", () -> new CommonLimeLeavesBlock());
	public static final RegistryObject<Block> COMMON_LIME_STAIRS = REGISTRY.register("common_lime_stairs", () -> new CommonLimeStairsBlock());
	public static final RegistryObject<Block> COMMON_LIME_SLAB = REGISTRY.register("common_lime_slab", () -> new CommonLimeSlabBlock());
	public static final RegistryObject<Block> COMMON_LIME_FENCE = REGISTRY.register("common_lime_fence", () -> new CommonLimeFenceBlock());
	public static final RegistryObject<Block> COMMON_LIME_FENCE_GATE = REGISTRY.register("common_lime_fence_gate", () -> new CommonLimeFenceGateBlock());
	public static final RegistryObject<Block> COMMON_LIME_PRESSURE_PLATE = REGISTRY.register("common_lime_pressure_plate", () -> new CommonLimePressurePlateBlock());
	public static final RegistryObject<Block> COMMON_LIME_BUTTON = REGISTRY.register("common_lime_button", () -> new CommonLimeButtonBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_WOOD = REGISTRY.register("field_maple_wood", () -> new FieldMapleWoodBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_LOG = REGISTRY.register("field_maple_log", () -> new FieldMapleLogBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_PLANKS = REGISTRY.register("field_maple_planks", () -> new FieldMaplePlanksBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_LEAVES = REGISTRY.register("field_maple_leaves", () -> new FieldMapleLeavesBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_STAIRS = REGISTRY.register("field_maple_stairs", () -> new FieldMapleStairsBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_SLAB = REGISTRY.register("field_maple_slab", () -> new FieldMapleSlabBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_FENCE = REGISTRY.register("field_maple_fence", () -> new FieldMapleFenceBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_FENCE_GATE = REGISTRY.register("field_maple_fence_gate", () -> new FieldMapleFenceGateBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_PRESSURE_PLATE = REGISTRY.register("field_maple_pressure_plate", () -> new FieldMaplePressurePlateBlock());
	public static final RegistryObject<Block> FIELD_MAPLE_BUTTON = REGISTRY.register("field_maple_button", () -> new FieldMapleButtonBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_WOOD = REGISTRY.register("plymouth_pear_wood", () -> new PlymouthPearWoodBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_LOG = REGISTRY.register("plymouth_pear_log", () -> new PlymouthPearLogBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_PLANKS = REGISTRY.register("plymouth_pear_planks", () -> new PlymouthPearPlanksBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_LEAVES = REGISTRY.register("plymouth_pear_leaves", () -> new PlymouthPearLeavesBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_STAIRS = REGISTRY.register("plymouth_pear_stairs", () -> new PlymouthPearStairsBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_SLAB = REGISTRY.register("plymouth_pear_slab", () -> new PlymouthPearSlabBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_FENCE = REGISTRY.register("plymouth_pear_fence", () -> new PlymouthPearFenceBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_FENCE_GATE = REGISTRY.register("plymouth_pear_fence_gate", () -> new PlymouthPearFenceGateBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_PRESSURE_PLATE = REGISTRY.register("plymouth_pear_pressure_plate", () -> new PlymouthPearPressurePlateBlock());
	public static final RegistryObject<Block> PLYMOUTH_PEAR_BUTTON = REGISTRY.register("plymouth_pear_button", () -> new PlymouthPearButtonBlock());
	public static final RegistryObject<Block> SCOTS_PINE_WOOD = REGISTRY.register("scots_pine_wood", () -> new ScotsPineWoodBlock());
	public static final RegistryObject<Block> SCOTS_PINE_LOG = REGISTRY.register("scots_pine_log", () -> new ScotsPineLogBlock());
	public static final RegistryObject<Block> SCOTS_PINE_PLANKS = REGISTRY.register("scots_pine_planks", () -> new ScotsPinePlanksBlock());
	public static final RegistryObject<Block> SCOTS_PINE_LEAVES = REGISTRY.register("scots_pine_leaves", () -> new ScotsPineLeavesBlock());
	public static final RegistryObject<Block> SCOTS_PINE_STAIRS = REGISTRY.register("scots_pine_stairs", () -> new ScotsPineStairsBlock());
	public static final RegistryObject<Block> SCOTS_PINE_SLAB = REGISTRY.register("scots_pine_slab", () -> new ScotsPineSlabBlock());
	public static final RegistryObject<Block> SCOTS_PINE_FENCE = REGISTRY.register("scots_pine_fence", () -> new ScotsPineFenceBlock());
	public static final RegistryObject<Block> SCOTS_PINE_FENCE_GATE = REGISTRY.register("scots_pine_fence_gate", () -> new ScotsPineFenceGateBlock());
	public static final RegistryObject<Block> SCOTS_PINE_PRESSURE_PLATE = REGISTRY.register("scots_pine_pressure_plate", () -> new ScotsPinePressurePlateBlock());
	public static final RegistryObject<Block> SCOTS_PINE_BUTTON = REGISTRY.register("scots_pine_button", () -> new ScotsPineButtonBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_WOOD = REGISTRY.register("black_poplar_wood", () -> new BlackPoplarWoodBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_LOG = REGISTRY.register("black_poplar_log", () -> new BlackPoplarLogBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_PLANKS = REGISTRY.register("black_poplar_planks", () -> new BlackPoplarPlanksBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_LEAVES = REGISTRY.register("black_poplar_leaves", () -> new BlackPoplarLeavesBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_STAIRS = REGISTRY.register("black_poplar_stairs", () -> new BlackPoplarStairsBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_SLAB = REGISTRY.register("black_poplar_slab", () -> new BlackPoplarSlabBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_FENCE = REGISTRY.register("black_poplar_fence", () -> new BlackPoplarFenceBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_FENCE_GATE = REGISTRY.register("black_poplar_fence_gate", () -> new BlackPoplarFenceGateBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_PRESSURE_PLATE = REGISTRY.register("black_poplar_pressure_plate", () -> new BlackPoplarPressurePlateBlock());
	public static final RegistryObject<Block> BLACK_POPLAR_BUTTON = REGISTRY.register("black_poplar_button", () -> new BlackPoplarButtonBlock());
	public static final RegistryObject<Block> ROWAN_WOOD = REGISTRY.register("rowan_wood", () -> new RowanWoodBlock());
	public static final RegistryObject<Block> ROWAN_LOG = REGISTRY.register("rowan_log", () -> new RowanLogBlock());
	public static final RegistryObject<Block> ROWAN_PLANKS = REGISTRY.register("rowan_planks", () -> new RowanPlanksBlock());
	public static final RegistryObject<Block> ROWAN_LEAVES = REGISTRY.register("rowan_leaves", () -> new RowanLeavesBlock());
	public static final RegistryObject<Block> ROWAN_STAIRS = REGISTRY.register("rowan_stairs", () -> new RowanStairsBlock());
	public static final RegistryObject<Block> ROWAN_SLAB = REGISTRY.register("rowan_slab", () -> new RowanSlabBlock());
	public static final RegistryObject<Block> ROWAN_FENCE = REGISTRY.register("rowan_fence", () -> new RowanFenceBlock());
	public static final RegistryObject<Block> ROWAN_FENCE_GATE = REGISTRY.register("rowan_fence_gate", () -> new RowanFenceGateBlock());
	public static final RegistryObject<Block> ROWAN_PRESSURE_PLATE = REGISTRY.register("rowan_pressure_plate", () -> new RowanPressurePlateBlock());
	public static final RegistryObject<Block> ROWAN_BUTTON = REGISTRY.register("rowan_button", () -> new RowanButtonBlock());
	public static final RegistryObject<Block> SPINDLE_WOOD = REGISTRY.register("spindle_wood", () -> new SpindleWoodBlock());
	public static final RegistryObject<Block> SPINDLE_LOG = REGISTRY.register("spindle_log", () -> new SpindleLogBlock());
	public static final RegistryObject<Block> SPINDLE_PLANKS = REGISTRY.register("spindle_planks", () -> new SpindlePlanksBlock());
	public static final RegistryObject<Block> SPINDLE_LEAVES = REGISTRY.register("spindle_leaves", () -> new SpindleLeavesBlock());
	public static final RegistryObject<Block> SPINDLE_STAIRS = REGISTRY.register("spindle_stairs", () -> new SpindleStairsBlock());
	public static final RegistryObject<Block> SPINDLE_SLAB = REGISTRY.register("spindle_slab", () -> new SpindleSlabBlock());
	public static final RegistryObject<Block> SPINDLE_FENCE = REGISTRY.register("spindle_fence", () -> new SpindleFenceBlock());
	public static final RegistryObject<Block> SPINDLE_FENCE_GATE = REGISTRY.register("spindle_fence_gate", () -> new SpindleFenceGateBlock());
	public static final RegistryObject<Block> SPINDLE_PRESSURE_PLATE = REGISTRY.register("spindle_pressure_plate", () -> new SpindlePressurePlateBlock());
	public static final RegistryObject<Block> SPINDLE_BUTTON = REGISTRY.register("spindle_button", () -> new SpindleButtonBlock());
	public static final RegistryObject<Block> WHITEBEAM_WOOD = REGISTRY.register("whitebeam_wood", () -> new WhitebeamWoodBlock());
	public static final RegistryObject<Block> WHITEBEAM_LOG = REGISTRY.register("whitebeam_log", () -> new WhitebeamLogBlock());
	public static final RegistryObject<Block> WHITEBEAM_PLANKS = REGISTRY.register("whitebeam_planks", () -> new WhitebeamPlanksBlock());
	public static final RegistryObject<Block> WHITEBEAM_LEAVES = REGISTRY.register("whitebeam_leaves", () -> new WhitebeamLeavesBlock());
	public static final RegistryObject<Block> WHITEBEAM_STAIRS = REGISTRY.register("whitebeam_stairs", () -> new WhitebeamStairsBlock());
	public static final RegistryObject<Block> WHITEBEAM_SLAB = REGISTRY.register("whitebeam_slab", () -> new WhitebeamSlabBlock());
	public static final RegistryObject<Block> WHITEBEAM_FENCE = REGISTRY.register("whitebeam_fence", () -> new WhitebeamFenceBlock());
	public static final RegistryObject<Block> WHITEBEAM_FENCE_GATE = REGISTRY.register("whitebeam_fence_gate", () -> new WhitebeamFenceGateBlock());
	public static final RegistryObject<Block> WHITEBEAM_PRESSURE_PLATE = REGISTRY.register("whitebeam_pressure_plate", () -> new WhitebeamPressurePlateBlock());
	public static final RegistryObject<Block> WHITEBEAM_BUTTON = REGISTRY.register("whitebeam_button", () -> new WhitebeamButtonBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_WOOD = REGISTRY.register("arran_whitebeam_wood", () -> new ArranWhitebeamWoodBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_LOG = REGISTRY.register("arran_whitebeam_log", () -> new ArranWhitebeamLogBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_PLANKS = REGISTRY.register("arran_whitebeam_planks", () -> new ArranWhitebeamPlanksBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_LEAVES = REGISTRY.register("arran_whitebeam_leaves", () -> new ArranWhitebeamLeavesBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_STAIRS = REGISTRY.register("arran_whitebeam_stairs", () -> new ArranWhitebeamStairsBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_SLAB = REGISTRY.register("arran_whitebeam_slab", () -> new ArranWhitebeamSlabBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_FENCE = REGISTRY.register("arran_whitebeam_fence", () -> new ArranWhitebeamFenceBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_FENCE_GATE = REGISTRY.register("arran_whitebeam_fence_gate", () -> new ArranWhitebeamFenceGateBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_PRESSURE_PLATE = REGISTRY.register("arran_whitebeam_pressure_plate", () -> new ArranWhitebeamPressurePlateBlock());
	public static final RegistryObject<Block> ARRAN_WHITEBEAM_BUTTON = REGISTRY.register("arran_whitebeam_button", () -> new ArranWhitebeamButtonBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_WOOD = REGISTRY.register("black_whitebeam_wood", () -> new BlackWhitebeamWoodBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_LOG = REGISTRY.register("black_whitebeam_log", () -> new BlackWhitebeamLogBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_PLANKS = REGISTRY.register("black_whitebeam_planks", () -> new BlackWhitebeamPlanksBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_LEAVES = REGISTRY.register("black_whitebeam_leaves", () -> new BlackWhitebeamLeavesBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_STAIRS = REGISTRY.register("black_whitebeam_stairs", () -> new BlackWhitebeamStairsBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_SLAB = REGISTRY.register("black_whitebeam_slab", () -> new BlackWhitebeamSlabBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_FENCE = REGISTRY.register("black_whitebeam_fence", () -> new BlackWhitebeamFenceBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_FENCE_GATE = REGISTRY.register("black_whitebeam_fence_gate", () -> new BlackWhitebeamFenceGateBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_PRESSURE_PLATE = REGISTRY.register("black_whitebeam_pressure_plate", () -> new BlackWhitebeamPressurePlateBlock());
	public static final RegistryObject<Block> BLACK_WHITEBEAM_BUTTON = REGISTRY.register("black_whitebeam_button", () -> new BlackWhitebeamButtonBlock());
	public static final RegistryObject<Block> BAY_WILLOW_WOOD = REGISTRY.register("bay_willow_wood", () -> new BayWillowWoodBlock());
	public static final RegistryObject<Block> BAY_WILLOW_LOG = REGISTRY.register("bay_willow_log", () -> new BayWillowLogBlock());
	public static final RegistryObject<Block> BAY_WILLOW_PLANKS = REGISTRY.register("bay_willow_planks", () -> new BayWillowPlanksBlock());
	public static final RegistryObject<Block> BAY_WILLOW_LEAVES = REGISTRY.register("bay_willow_leaves", () -> new BayWillowLeavesBlock());
	public static final RegistryObject<Block> BAY_WILLOW_STAIRS = REGISTRY.register("bay_willow_stairs", () -> new BayWillowStairsBlock());
	public static final RegistryObject<Block> BAY_WILLOW_SLAB = REGISTRY.register("bay_willow_slab", () -> new BayWillowSlabBlock());
	public static final RegistryObject<Block> BAY_WILLOW_FENCE = REGISTRY.register("bay_willow_fence", () -> new BayWillowFenceBlock());
	public static final RegistryObject<Block> BAY_WILLOW_FENCE_GATE = REGISTRY.register("bay_willow_fence_gate", () -> new BayWillowFenceGateBlock());
	public static final RegistryObject<Block> BAY_WILLOW_PRESSURE_PLATE = REGISTRY.register("bay_willow_pressure_plate", () -> new BayWillowPressurePlateBlock());
	public static final RegistryObject<Block> BAY_WILLOW_BUTTON = REGISTRY.register("bay_willow_button", () -> new BayWillowButtonBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_WOOD = REGISTRY.register("goat_willow_wood", () -> new GoatWillowWoodBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_LOG = REGISTRY.register("goat_willow_log", () -> new GoatWillowLogBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_PLANKS = REGISTRY.register("goat_willow_planks", () -> new GoatWillowPlanksBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_LEAVES = REGISTRY.register("goat_willow_leaves", () -> new GoatWillowLeavesBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_STAIRS = REGISTRY.register("goat_willow_stairs", () -> new GoatWillowStairsBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_SLAB = REGISTRY.register("goat_willow_slab", () -> new GoatWillowSlabBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_FENCE = REGISTRY.register("goat_willow_fence", () -> new GoatWillowFenceBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_FENCE_GATE = REGISTRY.register("goat_willow_fence_gate", () -> new GoatWillowFenceGateBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_PRESSURE_PLATE = REGISTRY.register("goat_willow_pressure_plate", () -> new GoatWillowPressurePlateBlock());
	public static final RegistryObject<Block> GOAT_WILLOW_BUTTON = REGISTRY.register("goat_willow_button", () -> new GoatWillowButtonBlock());
	public static final RegistryObject<Block> GREY_WILLOW_WOOD = REGISTRY.register("grey_willow_wood", () -> new GreyWillowWoodBlock());
	public static final RegistryObject<Block> GREY_WILLOW_LOG = REGISTRY.register("grey_willow_log", () -> new GreyWillowLogBlock());
	public static final RegistryObject<Block> GREY_WILLOW_PLANKS = REGISTRY.register("grey_willow_planks", () -> new GreyWillowPlanksBlock());
	public static final RegistryObject<Block> GREY_WILLOW_LEAVES = REGISTRY.register("grey_willow_leaves", () -> new GreyWillowLeavesBlock());
	public static final RegistryObject<Block> GREY_WILLOW_STAIRS = REGISTRY.register("grey_willow_stairs", () -> new GreyWillowStairsBlock());
	public static final RegistryObject<Block> GREY_WILLOW_SLAB = REGISTRY.register("grey_willow_slab", () -> new GreyWillowSlabBlock());
	public static final RegistryObject<Block> GREY_WILLOW_FENCE = REGISTRY.register("grey_willow_fence", () -> new GreyWillowFenceBlock());
	public static final RegistryObject<Block> GREY_WILLOW_FENCE_GATE = REGISTRY.register("grey_willow_fence_gate", () -> new GreyWillowFenceGateBlock());
	public static final RegistryObject<Block> GREY_WILLOW_PRESSURE_PLATE = REGISTRY.register("grey_willow_pressure_plate", () -> new GreyWillowPressurePlateBlock());
	public static final RegistryObject<Block> GREY_WILLOW_BUTTON = REGISTRY.register("grey_willow_button", () -> new GreyWillowButtonBlock());
	public static final RegistryObject<Block> SAMPIRE = REGISTRY.register("sampire", () -> new SampireBlock());
	public static final RegistryObject<Block> BLUEBELLS = REGISTRY.register("bluebells", () -> new BluebellsBlock());
	public static final RegistryObject<Block> ALDER_LEAVES = REGISTRY.register("alder_leaves", () -> new AlderLeavesBlock());
	public static final RegistryObject<Block> ALDER_WOOD_PLANKS = REGISTRY.register("alder_wood_planks", () -> new AlderWoodPlanksBlock());
}
