
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.foragecraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.foragecraft.item.NettleSoupItem;
import net.mcreator.foragecraft.item.HawthornBerryItem;
import net.mcreator.foragecraft.item.ForagersManualItem;
import net.mcreator.foragecraft.item.ForagersIngotItem;
import net.mcreator.foragecraft.item.BasketItem;
import net.mcreator.foragecraft.ForagecraftMod;

public class ForagecraftModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ForagecraftMod.MODID);
	public static final RegistryObject<Item> NETTLE = block(ForagecraftModBlocks.NETTLE, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DANDELION = block(ForagecraftModBlocks.DANDELION, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> NETTLE_SOUP = REGISTRY.register("nettle_soup", () -> new NettleSoupItem());
	public static final RegistryObject<Item> WILD_GARLIC = block(ForagecraftModBlocks.WILD_GARLIC, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WOOD_SORREL = block(ForagecraftModBlocks.WOOD_SORREL, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> HEMLOCK = block(ForagecraftModBlocks.HEMLOCK, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BASKET = REGISTRY.register("basket", () -> new BasketItem());
	public static final RegistryObject<Item> FORAGERS_INGOT = REGISTRY.register("foragers_ingot", () -> new ForagersIngotItem());
	public static final RegistryObject<Item> CEP = block(ForagecraftModBlocks.CEP, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLEWIT = block(ForagecraftModBlocks.BLEWIT, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PUFFBALL = block(ForagecraftModBlocks.PUFFBALL, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FLY_AGARIC = block(ForagecraftModBlocks.FLY_AGARIC, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PARASOL_MUSHROOM = block(ForagecraftModBlocks.PARASOL_MUSHROOM, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> CHANTERELLE = block(ForagecraftModBlocks.CHANTERELLE, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DEHYDRATOR = block(ForagecraftModBlocks.DEHYDRATOR, ForagecraftModTabs.TAB_FORAGE_CRAFT_BLOCKS);
	public static final RegistryObject<Item> CAMPFIRE = block(ForagecraftModBlocks.CAMPFIRE, ForagecraftModTabs.TAB_FORAGE_CRAFT_BLOCKS);
	public static final RegistryObject<Item> COOKING_POT = block(ForagecraftModBlocks.COOKING_POT, ForagecraftModTabs.TAB_FORAGE_CRAFT_TOOLS);
	public static final RegistryObject<Item> MYCE_SPAWN_EGG = REGISTRY.register("myce_spawn_egg", () -> new ForgeSpawnEggItem(ForagecraftModEntities.MYCE, -1, -1, new Item.Properties().tab(ForagecraftModTabs.TAB_FORAGE_CRAFT_ANIMALS)));
	public static final RegistryObject<Item> BADGER_SPAWN_EGG = REGISTRY.register("badger_spawn_egg", () -> new ForgeSpawnEggItem(ForagecraftModEntities.BADGER, -1, -16777216, new Item.Properties().tab(ForagecraftModTabs.TAB_FORAGE_CRAFT_ANIMALS)));
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_PLANKS = block(ForagecraftModBlocks.COMMON_BEECH_WOOD_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_LOG = block(ForagecraftModBlocks.COMMON_BEECH_WOOD_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_SAPLING = block(ForagecraftModBlocks.COMMON_BEECH_SAPLING, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_LEAVES = block(ForagecraftModBlocks.COMMON_BEECH_LEAVES, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_STAIRS = block(ForagecraftModBlocks.COMMON_BEECH_WOOD_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_SLAB = block(ForagecraftModBlocks.COMMON_BEECH_WOOD_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_FENCE = block(ForagecraftModBlocks.COMMON_BEECH_WOOD_FENCE, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_FENCE_GATE = block(ForagecraftModBlocks.COMMON_BEECH_WOOD_FENCE_GATE, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_TRAPDOOR = block(ForagecraftModBlocks.COMMON_BEECH_WOOD_TRAPDOOR, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> COMMON_BEECH_WOOD_DOOR = doubleBlock(ForagecraftModBlocks.COMMON_BEECH_WOOD_DOOR, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> HAWTHORNLOG = block(ForagecraftModBlocks.HAWTHORNLOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> HAWTHORNLEAVES = block(ForagecraftModBlocks.HAWTHORNLEAVES, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> HAWTHORNLEAVESBERRIES = block(ForagecraftModBlocks.HAWTHORNLEAVESBERRIES, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> HAWTHORNPLANK = block(ForagecraftModBlocks.HAWTHORNPLANK, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> HAWTHORN_SAPLING = block(ForagecraftModBlocks.HAWTHORN_SAPLING, ForagecraftModTabs.TAB_FORAGE_CRAFT_TREES);
	public static final RegistryObject<Item> HAWTHORN_BERRY = REGISTRY.register("hawthorn_berry", () -> new HawthornBerryItem());
	public static final RegistryObject<Item> YEW_WOOD = block(ForagecraftModBlocks.YEW_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ALDERWOODLOG = block(ForagecraftModBlocks.ALDERWOODLOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> YEW_LOG = block(ForagecraftModBlocks.YEW_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> YEW_PLANKS = block(ForagecraftModBlocks.YEW_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> YEW_LEAVES = block(ForagecraftModBlocks.YEW_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> YEW_STAIRS = block(ForagecraftModBlocks.YEW_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> YEW_SLAB = block(ForagecraftModBlocks.YEW_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> YEW_FENCE = block(ForagecraftModBlocks.YEW_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> YEW_FENCE_GATE = block(ForagecraftModBlocks.YEW_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> YEW_PRESSURE_PLATE = block(ForagecraftModBlocks.YEW_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> YEW_BUTTON = block(ForagecraftModBlocks.YEW_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASH_WOOD = block(ForagecraftModBlocks.ASH_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASH_LOG = block(ForagecraftModBlocks.ASH_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASH_PLANKS = block(ForagecraftModBlocks.ASH_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASH_LEAVES = block(ForagecraftModBlocks.ASH_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ASH_STAIRS = block(ForagecraftModBlocks.ASH_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASH_SLAB = block(ForagecraftModBlocks.ASH_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASH_FENCE = block(ForagecraftModBlocks.ASH_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ASH_FENCE_GATE = block(ForagecraftModBlocks.ASH_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ASH_PRESSURE_PLATE = block(ForagecraftModBlocks.ASH_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ASH_BUTTON = block(ForagecraftModBlocks.ASH_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASPEN_WOOD = block(ForagecraftModBlocks.ASPEN_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASPEN_LOG = block(ForagecraftModBlocks.ASPEN_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASPEN_PLANKS = block(ForagecraftModBlocks.ASPEN_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASPEN_LEAVES = block(ForagecraftModBlocks.ASPEN_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ASPEN_STAIRS = block(ForagecraftModBlocks.ASPEN_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASPEN_SLAB = block(ForagecraftModBlocks.ASPEN_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ASPEN_FENCE = block(ForagecraftModBlocks.ASPEN_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ASPEN_FENCE_GATE = block(ForagecraftModBlocks.ASPEN_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ASPEN_PRESSURE_PLATE = block(ForagecraftModBlocks.ASPEN_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ASPEN_BUTTON = block(ForagecraftModBlocks.ASPEN_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DOWNY_BIRCH_WOOD = block(ForagecraftModBlocks.DOWNY_BIRCH_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DOWNY_BIRCH_LOG = block(ForagecraftModBlocks.DOWNY_BIRCH_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DOWNY_BIRCH_PLANKS = block(ForagecraftModBlocks.DOWNY_BIRCH_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DOWNY_BIRCH_LEAVES = block(ForagecraftModBlocks.DOWNY_BIRCH_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> DOWNY_BIRCH_STAIRS = block(ForagecraftModBlocks.DOWNY_BIRCH_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DOWNY_BIRCH_SLAB = block(ForagecraftModBlocks.DOWNY_BIRCH_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> DOWNY_BIRCH_FENCE = block(ForagecraftModBlocks.DOWNY_BIRCH_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> DOWNY_BIRCH_FENCE_GATE = block(ForagecraftModBlocks.DOWNY_BIRCH_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> DOWNY_BIRCH_PRESSURE_PLATE = block(ForagecraftModBlocks.DOWNY_BIRCH_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> DOWNY_BIRCH_BUTTON = block(ForagecraftModBlocks.DOWNY_BIRCH_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_WOOD = block(ForagecraftModBlocks.PURGING_BUCKTHORN_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_LOG = block(ForagecraftModBlocks.PURGING_BUCKTHORN_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_PLANKS = block(ForagecraftModBlocks.PURGING_BUCKTHORN_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_LEAVES = block(ForagecraftModBlocks.PURGING_BUCKTHORN_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_STAIRS = block(ForagecraftModBlocks.PURGING_BUCKTHORN_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_SLAB = block(ForagecraftModBlocks.PURGING_BUCKTHORN_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_FENCE = block(ForagecraftModBlocks.PURGING_BUCKTHORN_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_FENCE_GATE = block(ForagecraftModBlocks.PURGING_BUCKTHORN_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_PRESSURE_PLATE = block(ForagecraftModBlocks.PURGING_BUCKTHORN_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PURGING_BUCKTHORN_BUTTON = block(ForagecraftModBlocks.PURGING_BUCKTHORN_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BIRD_CHERRY_WOOD = block(ForagecraftModBlocks.BIRD_CHERRY_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BIRD_CHERRY_LOG = block(ForagecraftModBlocks.BIRD_CHERRY_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BIRD_CHERRY_PLANKS = block(ForagecraftModBlocks.BIRD_CHERRY_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BIRD_CHERRY_LEAVES = block(ForagecraftModBlocks.BIRD_CHERRY_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BIRD_CHERRY_STAIRS = block(ForagecraftModBlocks.BIRD_CHERRY_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BIRD_CHERRY_SLAB = block(ForagecraftModBlocks.BIRD_CHERRY_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BIRD_CHERRY_FENCE = block(ForagecraftModBlocks.BIRD_CHERRY_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BIRD_CHERRY_FENCE_GATE = block(ForagecraftModBlocks.BIRD_CHERRY_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BIRD_CHERRY_PRESSURE_PLATE = block(ForagecraftModBlocks.BIRD_CHERRY_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BIRD_CHERRY_BUTTON = block(ForagecraftModBlocks.BIRD_CHERRY_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WILD_CHERRY_WOOD = block(ForagecraftModBlocks.WILD_CHERRY_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WILD_CHERRY_LOG = block(ForagecraftModBlocks.WILD_CHERRY_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WILD_CHERRY_PLANKS = block(ForagecraftModBlocks.WILD_CHERRY_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WILD_CHERRY_LEAVES = block(ForagecraftModBlocks.WILD_CHERRY_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WILD_CHERRY_STAIRS = block(ForagecraftModBlocks.WILD_CHERRY_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WILD_CHERRY_SLAB = block(ForagecraftModBlocks.WILD_CHERRY_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WILD_CHERRY_FENCE = block(ForagecraftModBlocks.WILD_CHERRY_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WILD_CHERRY_FENCE_GATE = block(ForagecraftModBlocks.WILD_CHERRY_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WILD_CHERRY_PRESSURE_PLATE = block(ForagecraftModBlocks.WILD_CHERRY_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WILD_CHERRY_BUTTON = block(ForagecraftModBlocks.WILD_CHERRY_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> CRABAPPLE_WOOD = block(ForagecraftModBlocks.CRABAPPLE_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> CRABAPPLE_LOG = block(ForagecraftModBlocks.CRABAPPLE_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> CRABAPPLE_PLANKS = block(ForagecraftModBlocks.CRABAPPLE_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> CRABAPPLE_LEAVES = block(ForagecraftModBlocks.CRABAPPLE_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CRABAPPLE_STAIRS = block(ForagecraftModBlocks.CRABAPPLE_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> CRABAPPLE_SLAB = block(ForagecraftModBlocks.CRABAPPLE_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> CRABAPPLE_FENCE = block(ForagecraftModBlocks.CRABAPPLE_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CRABAPPLE_FENCE_GATE = block(ForagecraftModBlocks.CRABAPPLE_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CRABAPPLE_PRESSURE_PLATE = block(ForagecraftModBlocks.CRABAPPLE_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CRABAPPLE_BUTTON = block(ForagecraftModBlocks.CRABAPPLE_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ELDER_WOOD = block(ForagecraftModBlocks.ELDER_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ELDER_LOG = block(ForagecraftModBlocks.ELDER_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ELDER_PLANKS = block(ForagecraftModBlocks.ELDER_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ELDER_LEAVES = block(ForagecraftModBlocks.ELDER_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ELDER_STAIRS = block(ForagecraftModBlocks.ELDER_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ELDER_SLAB = block(ForagecraftModBlocks.ELDER_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ELDER_FENCE = block(ForagecraftModBlocks.ELDER_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ELDER_FENCE_GATE = block(ForagecraftModBlocks.ELDER_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ELDER_PRESSURE_PLATE = block(ForagecraftModBlocks.ELDER_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ELDER_BUTTON = block(ForagecraftModBlocks.ELDER_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ENGLISH_ELM_WOOD = block(ForagecraftModBlocks.ENGLISH_ELM_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ENGLISH_ELM_LOG = block(ForagecraftModBlocks.ENGLISH_ELM_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ENGLISH_ELM_PLANKS = block(ForagecraftModBlocks.ENGLISH_ELM_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ENGLISH_ELM_LEAVES = block(ForagecraftModBlocks.ENGLISH_ELM_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ENGLISH_ELM_STAIRS = block(ForagecraftModBlocks.ENGLISH_ELM_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ENGLISH_ELM_SLAB = block(ForagecraftModBlocks.ENGLISH_ELM_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ENGLISH_ELM_FENCE = block(ForagecraftModBlocks.ENGLISH_ELM_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ENGLISH_ELM_FENCE_GATE = block(ForagecraftModBlocks.ENGLISH_ELM_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ENGLISH_ELM_PRESSURE_PLATE = block(ForagecraftModBlocks.ENGLISH_ELM_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ENGLISH_ELM_BUTTON = block(ForagecraftModBlocks.ENGLISH_ELM_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WYCH_ELM_WOOD = block(ForagecraftModBlocks.WYCH_ELM_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WYCH_ELM_LOG = block(ForagecraftModBlocks.WYCH_ELM_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WYCH_ELM_PLANKS = block(ForagecraftModBlocks.WYCH_ELM_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WYCH_ELM_LEAVES = block(ForagecraftModBlocks.WYCH_ELM_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WYCH_ELM_STAIRS = block(ForagecraftModBlocks.WYCH_ELM_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WYCH_ELM_SLAB = block(ForagecraftModBlocks.WYCH_ELM_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WYCH_ELM_FENCE = block(ForagecraftModBlocks.WYCH_ELM_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WYCH_ELM_FENCE_GATE = block(ForagecraftModBlocks.WYCH_ELM_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WYCH_ELM_PRESSURE_PLATE = block(ForagecraftModBlocks.WYCH_ELM_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WYCH_ELM_BUTTON = block(ForagecraftModBlocks.WYCH_ELM_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> HORNBEAM_WOOD = block(ForagecraftModBlocks.HORNBEAM_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> HORNBEAM_LOG = block(ForagecraftModBlocks.HORNBEAM_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> HORNBEAM_PLANKS = block(ForagecraftModBlocks.HORNBEAM_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> HORNBEAM_LEAVES = block(ForagecraftModBlocks.HORNBEAM_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> HORNBEAM_STAIRS = block(ForagecraftModBlocks.HORNBEAM_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> HORNBEAM_SLAB = block(ForagecraftModBlocks.HORNBEAM_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> HORNBEAM_FENCE = block(ForagecraftModBlocks.HORNBEAM_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> HORNBEAM_FENCE_GATE = block(ForagecraftModBlocks.HORNBEAM_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> HORNBEAM_PRESSURE_PLATE = block(ForagecraftModBlocks.HORNBEAM_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> HORNBEAM_BUTTON = block(ForagecraftModBlocks.HORNBEAM_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> JUNIPER_WOOD = block(ForagecraftModBlocks.JUNIPER_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> JUNIPER_LOG = block(ForagecraftModBlocks.JUNIPER_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> JUNIPER_PLANKS = block(ForagecraftModBlocks.JUNIPER_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> JUNIPER_LEAVES = block(ForagecraftModBlocks.JUNIPER_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> JUNIPER_STAIRS = block(ForagecraftModBlocks.JUNIPER_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> JUNIPER_SLAB = block(ForagecraftModBlocks.JUNIPER_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> JUNIPER_FENCE = block(ForagecraftModBlocks.JUNIPER_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> JUNIPER_FENCE_GATE = block(ForagecraftModBlocks.JUNIPER_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> JUNIPER_PRESSURE_PLATE = block(ForagecraftModBlocks.JUNIPER_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> JUNIPER_BUTTON = block(ForagecraftModBlocks.JUNIPER_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> COMMON_LIME_WOOD = block(ForagecraftModBlocks.COMMON_LIME_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> COMMON_LIME_LOG = block(ForagecraftModBlocks.COMMON_LIME_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> COMMON_LIME_PLANKS = block(ForagecraftModBlocks.COMMON_LIME_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> COMMON_LIME_LEAVES = block(ForagecraftModBlocks.COMMON_LIME_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> COMMON_LIME_STAIRS = block(ForagecraftModBlocks.COMMON_LIME_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> COMMON_LIME_SLAB = block(ForagecraftModBlocks.COMMON_LIME_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> COMMON_LIME_FENCE = block(ForagecraftModBlocks.COMMON_LIME_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> COMMON_LIME_FENCE_GATE = block(ForagecraftModBlocks.COMMON_LIME_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> COMMON_LIME_PRESSURE_PLATE = block(ForagecraftModBlocks.COMMON_LIME_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> COMMON_LIME_BUTTON = block(ForagecraftModBlocks.COMMON_LIME_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FIELD_MAPLE_WOOD = block(ForagecraftModBlocks.FIELD_MAPLE_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FIELD_MAPLE_LOG = block(ForagecraftModBlocks.FIELD_MAPLE_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FIELD_MAPLE_PLANKS = block(ForagecraftModBlocks.FIELD_MAPLE_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FIELD_MAPLE_LEAVES = block(ForagecraftModBlocks.FIELD_MAPLE_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> FIELD_MAPLE_STAIRS = block(ForagecraftModBlocks.FIELD_MAPLE_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FIELD_MAPLE_SLAB = block(ForagecraftModBlocks.FIELD_MAPLE_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FIELD_MAPLE_FENCE = block(ForagecraftModBlocks.FIELD_MAPLE_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> FIELD_MAPLE_FENCE_GATE = block(ForagecraftModBlocks.FIELD_MAPLE_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> FIELD_MAPLE_PRESSURE_PLATE = block(ForagecraftModBlocks.FIELD_MAPLE_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> FIELD_MAPLE_BUTTON = block(ForagecraftModBlocks.FIELD_MAPLE_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_WOOD = block(ForagecraftModBlocks.PLYMOUTH_PEAR_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_LOG = block(ForagecraftModBlocks.PLYMOUTH_PEAR_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_PLANKS = block(ForagecraftModBlocks.PLYMOUTH_PEAR_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_LEAVES = block(ForagecraftModBlocks.PLYMOUTH_PEAR_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_STAIRS = block(ForagecraftModBlocks.PLYMOUTH_PEAR_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_SLAB = block(ForagecraftModBlocks.PLYMOUTH_PEAR_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_FENCE = block(ForagecraftModBlocks.PLYMOUTH_PEAR_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_FENCE_GATE = block(ForagecraftModBlocks.PLYMOUTH_PEAR_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_PRESSURE_PLATE = block(ForagecraftModBlocks.PLYMOUTH_PEAR_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PLYMOUTH_PEAR_BUTTON = block(ForagecraftModBlocks.PLYMOUTH_PEAR_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SCOTS_PINE_WOOD = block(ForagecraftModBlocks.SCOTS_PINE_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SCOTS_PINE_LOG = block(ForagecraftModBlocks.SCOTS_PINE_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SCOTS_PINE_PLANKS = block(ForagecraftModBlocks.SCOTS_PINE_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SCOTS_PINE_LEAVES = block(ForagecraftModBlocks.SCOTS_PINE_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> SCOTS_PINE_STAIRS = block(ForagecraftModBlocks.SCOTS_PINE_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SCOTS_PINE_SLAB = block(ForagecraftModBlocks.SCOTS_PINE_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SCOTS_PINE_FENCE = block(ForagecraftModBlocks.SCOTS_PINE_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> SCOTS_PINE_FENCE_GATE = block(ForagecraftModBlocks.SCOTS_PINE_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> SCOTS_PINE_PRESSURE_PLATE = block(ForagecraftModBlocks.SCOTS_PINE_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> SCOTS_PINE_BUTTON = block(ForagecraftModBlocks.SCOTS_PINE_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_POPLAR_WOOD = block(ForagecraftModBlocks.BLACK_POPLAR_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_POPLAR_LOG = block(ForagecraftModBlocks.BLACK_POPLAR_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_POPLAR_PLANKS = block(ForagecraftModBlocks.BLACK_POPLAR_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_POPLAR_LEAVES = block(ForagecraftModBlocks.BLACK_POPLAR_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLACK_POPLAR_STAIRS = block(ForagecraftModBlocks.BLACK_POPLAR_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_POPLAR_SLAB = block(ForagecraftModBlocks.BLACK_POPLAR_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_POPLAR_FENCE = block(ForagecraftModBlocks.BLACK_POPLAR_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLACK_POPLAR_FENCE_GATE = block(ForagecraftModBlocks.BLACK_POPLAR_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BLACK_POPLAR_PRESSURE_PLATE = block(ForagecraftModBlocks.BLACK_POPLAR_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BLACK_POPLAR_BUTTON = block(ForagecraftModBlocks.BLACK_POPLAR_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ROWAN_WOOD = block(ForagecraftModBlocks.ROWAN_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ROWAN_LOG = block(ForagecraftModBlocks.ROWAN_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ROWAN_PLANKS = block(ForagecraftModBlocks.ROWAN_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ROWAN_LEAVES = block(ForagecraftModBlocks.ROWAN_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ROWAN_STAIRS = block(ForagecraftModBlocks.ROWAN_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ROWAN_SLAB = block(ForagecraftModBlocks.ROWAN_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ROWAN_FENCE = block(ForagecraftModBlocks.ROWAN_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ROWAN_FENCE_GATE = block(ForagecraftModBlocks.ROWAN_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ROWAN_PRESSURE_PLATE = block(ForagecraftModBlocks.ROWAN_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ROWAN_BUTTON = block(ForagecraftModBlocks.ROWAN_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SPINDLE_WOOD = block(ForagecraftModBlocks.SPINDLE_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SPINDLE_LOG = block(ForagecraftModBlocks.SPINDLE_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SPINDLE_PLANKS = block(ForagecraftModBlocks.SPINDLE_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SPINDLE_LEAVES = block(ForagecraftModBlocks.SPINDLE_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> SPINDLE_STAIRS = block(ForagecraftModBlocks.SPINDLE_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SPINDLE_SLAB = block(ForagecraftModBlocks.SPINDLE_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SPINDLE_FENCE = block(ForagecraftModBlocks.SPINDLE_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> SPINDLE_FENCE_GATE = block(ForagecraftModBlocks.SPINDLE_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> SPINDLE_PRESSURE_PLATE = block(ForagecraftModBlocks.SPINDLE_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> SPINDLE_BUTTON = block(ForagecraftModBlocks.SPINDLE_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WHITEBEAM_WOOD = block(ForagecraftModBlocks.WHITEBEAM_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WHITEBEAM_LOG = block(ForagecraftModBlocks.WHITEBEAM_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WHITEBEAM_PLANKS = block(ForagecraftModBlocks.WHITEBEAM_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WHITEBEAM_LEAVES = block(ForagecraftModBlocks.WHITEBEAM_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WHITEBEAM_STAIRS = block(ForagecraftModBlocks.WHITEBEAM_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WHITEBEAM_SLAB = block(ForagecraftModBlocks.WHITEBEAM_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> WHITEBEAM_FENCE = block(ForagecraftModBlocks.WHITEBEAM_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WHITEBEAM_FENCE_GATE = block(ForagecraftModBlocks.WHITEBEAM_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WHITEBEAM_PRESSURE_PLATE = block(ForagecraftModBlocks.WHITEBEAM_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WHITEBEAM_BUTTON = block(ForagecraftModBlocks.WHITEBEAM_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_WOOD = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_LOG = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_PLANKS = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_LEAVES = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_STAIRS = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_SLAB = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_FENCE = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_FENCE_GATE = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_PRESSURE_PLATE = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ARRAN_WHITEBEAM_BUTTON = block(ForagecraftModBlocks.ARRAN_WHITEBEAM_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_WOOD = block(ForagecraftModBlocks.BLACK_WHITEBEAM_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_LOG = block(ForagecraftModBlocks.BLACK_WHITEBEAM_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_PLANKS = block(ForagecraftModBlocks.BLACK_WHITEBEAM_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_LEAVES = block(ForagecraftModBlocks.BLACK_WHITEBEAM_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_STAIRS = block(ForagecraftModBlocks.BLACK_WHITEBEAM_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_SLAB = block(ForagecraftModBlocks.BLACK_WHITEBEAM_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_FENCE = block(ForagecraftModBlocks.BLACK_WHITEBEAM_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_FENCE_GATE = block(ForagecraftModBlocks.BLACK_WHITEBEAM_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_PRESSURE_PLATE = block(ForagecraftModBlocks.BLACK_WHITEBEAM_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BLACK_WHITEBEAM_BUTTON = block(ForagecraftModBlocks.BLACK_WHITEBEAM_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BAY_WILLOW_WOOD = block(ForagecraftModBlocks.BAY_WILLOW_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BAY_WILLOW_LOG = block(ForagecraftModBlocks.BAY_WILLOW_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BAY_WILLOW_PLANKS = block(ForagecraftModBlocks.BAY_WILLOW_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BAY_WILLOW_LEAVES = block(ForagecraftModBlocks.BAY_WILLOW_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BAY_WILLOW_STAIRS = block(ForagecraftModBlocks.BAY_WILLOW_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BAY_WILLOW_SLAB = block(ForagecraftModBlocks.BAY_WILLOW_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BAY_WILLOW_FENCE = block(ForagecraftModBlocks.BAY_WILLOW_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BAY_WILLOW_FENCE_GATE = block(ForagecraftModBlocks.BAY_WILLOW_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BAY_WILLOW_PRESSURE_PLATE = block(ForagecraftModBlocks.BAY_WILLOW_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BAY_WILLOW_BUTTON = block(ForagecraftModBlocks.BAY_WILLOW_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GOAT_WILLOW_WOOD = block(ForagecraftModBlocks.GOAT_WILLOW_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GOAT_WILLOW_LOG = block(ForagecraftModBlocks.GOAT_WILLOW_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GOAT_WILLOW_PLANKS = block(ForagecraftModBlocks.GOAT_WILLOW_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GOAT_WILLOW_LEAVES = block(ForagecraftModBlocks.GOAT_WILLOW_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> GOAT_WILLOW_STAIRS = block(ForagecraftModBlocks.GOAT_WILLOW_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GOAT_WILLOW_SLAB = block(ForagecraftModBlocks.GOAT_WILLOW_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GOAT_WILLOW_FENCE = block(ForagecraftModBlocks.GOAT_WILLOW_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> GOAT_WILLOW_FENCE_GATE = block(ForagecraftModBlocks.GOAT_WILLOW_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> GOAT_WILLOW_PRESSURE_PLATE = block(ForagecraftModBlocks.GOAT_WILLOW_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> GOAT_WILLOW_BUTTON = block(ForagecraftModBlocks.GOAT_WILLOW_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GREY_WILLOW_WOOD = block(ForagecraftModBlocks.GREY_WILLOW_WOOD, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GREY_WILLOW_LOG = block(ForagecraftModBlocks.GREY_WILLOW_LOG, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GREY_WILLOW_PLANKS = block(ForagecraftModBlocks.GREY_WILLOW_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GREY_WILLOW_LEAVES = block(ForagecraftModBlocks.GREY_WILLOW_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> GREY_WILLOW_STAIRS = block(ForagecraftModBlocks.GREY_WILLOW_STAIRS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GREY_WILLOW_SLAB = block(ForagecraftModBlocks.GREY_WILLOW_SLAB, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> GREY_WILLOW_FENCE = block(ForagecraftModBlocks.GREY_WILLOW_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> GREY_WILLOW_FENCE_GATE = block(ForagecraftModBlocks.GREY_WILLOW_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> GREY_WILLOW_PRESSURE_PLATE = block(ForagecraftModBlocks.GREY_WILLOW_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> GREY_WILLOW_BUTTON = block(ForagecraftModBlocks.GREY_WILLOW_BUTTON, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> SAMPIRE = block(ForagecraftModBlocks.SAMPIRE, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> BLUEBELLS = block(ForagecraftModBlocks.BLUEBELLS, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BABY_FALLOW_DEER_SPAWN_EGG = REGISTRY.register("baby_fallow_deer_spawn_egg",
			() -> new ForgeSpawnEggItem(ForagecraftModEntities.BABY_FALLOW_DEER, -8960504, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> FORAGERS_MANUAL = REGISTRY.register("foragers_manual", () -> new ForagersManualItem());
	public static final RegistryObject<Item> RED_SQUIRREL_SPAWN_EGG = REGISTRY.register("red_squirrel_spawn_egg",
			() -> new ForgeSpawnEggItem(ForagecraftModEntities.RED_SQUIRREL, -35584, -11653374, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> ROBIN_SPAWN_EGG = REGISTRY.register("robin_spawn_egg", () -> new ForgeSpawnEggItem(ForagecraftModEntities.ROBIN, -1, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> ALDER_LEAVES = block(ForagecraftModBlocks.ALDER_LEAVES, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> ALDER_WOOD_PLANKS = block(ForagecraftModBlocks.ALDER_WOOD_PLANKS, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);
	public static final RegistryObject<Item> FALLOW_DEER_SPAWN_EGG = REGISTRY.register("fallow_deer_spawn_egg", () -> new ForgeSpawnEggItem(ForagecraftModEntities.FALLOW_DEER, -1, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> TEST_SPAWN_EGG = REGISTRY.register("test_spawn_egg", () -> new ForgeSpawnEggItem(ForagecraftModEntities.TEST, -1, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> FLY_AGARIC_BLOCK = block(ForagecraftModBlocks.FLY_AGARIC_BLOCK, ForagecraftModTabs.TAB_FORAGE_CRAFT_PLANTS);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
